spring:
  datasource:
    url: jdbc:h2:file:D:/dev/util/h2db/microservicedb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: MsaHikariConnectionPool
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 25000
      max-lifetime: 30000
      validation-timeout: 10000
      driver-class-name: org.h2.Driver
      username: sa
      password:
    tomcat:
      max-wait: 3000
      max-active: 10
      max-idle: 10
      min-idle: 10
      initial-size: 10
      commit-on-return: true
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  data:
    rest:
      base-path: api
  rabbitmq:
    host: localhost
    port: 5672
    username: you-dev
    password: 1234
    virtual-host: ccm-dev-vhost

msa:
 service : msa
 port : 8080    